#!/usr/bin/env python

import argparse
import json
import sys

import fastavro
import pymetastore.metastore

import utils

parser = argparse.ArgumentParser()
parser.add_argument('database_name')
parser.add_argument('table_name')
parser.add_argument('--hms-host', default='localhost')
parser.add_argument('--hms-port', default=9083)
args = parser.parse_args()

with pymetastore.metastore.HMS.create(host=args.hms_host, port=args.hms_port) as hms:
    try:
        table = hms.get_table(
            database_name=args.database_name,
            table_name=args.table_name,
        )
    except pymetastore.hive_metastore.ttypes.NoSuchObjectException:
        print(f'Table {args.table_name} does not exist', file=sys.stderr)
        sys.exit(1)
    s3_table_metadata_bucket, s3_table_metadata_key = utils.parse_s3a(table.parameters['metadata_location'])
    table_metadata = json.loads(utils.s3_get(s3_table_metadata_bucket, s3_table_metadata_key))
    # Assumption: last version is latest version
    # Better approach: current-snapshot-id
    s3_manifest_list_bucket, s3_manifest_list_key = utils.parse_s3a(table_metadata['snapshots'][-1]['manifest-list'])
    manifest_list_reader = fastavro.reader(utils.s3_get(s3_manifest_list_bucket, s3_manifest_list_key, binary=True))
    data_files = []
    for manifest_list in manifest_list_reader:
        s3_manifest_bucket, s3_manifest_key = utils.parse_s3a(manifest_list['manifest_path'])
        manifest_reader = fastavro.reader(utils.s3_get(s3_manifest_bucket, s3_manifest_key, binary=True))
        for manifest in manifest_reader:
            if manifest['status'] == 1:
                data_files.append(manifest['data_file']['file_path'])
    for data_file in data_files:
        print(f'{data_file}')
